module.exports = {
  projects: [
    '<rootDir>/apps/reslife-app',
    '<rootDir>/apps/reslife-request',
    '<rootDir>/libs/reslife-main/welcome',
    '<rootDir>/libs/shared/ui',
    '<rootDir>/libs/reslife-main/check-in',
    '<rootDir>/libs/data',
    '<rootDir>/libs/check-ins/check-in-feature',
    '<rootDir>/libs/check-ins/check-in-data-access',
    '<rootDir>/libs/check-ins/check-in-ui',
    '<rootDir>/libs/check-ins/check-in-model',
    '<rootDir>/libs/utils',
    '<rootDir>/libs/welcome-feature',
    '<rootDir>/libs/shared-models',
    '<rootDir>/libs/boarder-management-feature',
    '<rootDir>/libs/admin/admin-ui',
    '<rootDir>/libs/admin/admin-data-access',
  ],
};
