name: Nx Affected CI
on:
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: git fetch origin main
        run: npm ci

      - name: Run Affected Tests
        shell: bash
        run: npm run affected:test -- --base=remotes/origin/main --parallel --maxParallel=5
      - name: Run Affected E2E Tests
        shell: bash
        run: npm run affected:e2e -- --base=remotes/origin/main
      - name: Lint 
        shell: bash
        run: npm run affected:lint -- --base=remotes/origin/main 